apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cluster/rook-ceph-cluster/
  - service-monitor.yaml
  - exporter-service-monitor.yaml
  - prometheus.yaml
  - prometheus-service.yaml
  - bridge-vlan-public-net.yaml
  - bridge-vlan-cluster-net.yaml  
generators:
  - ../../../../../helm/overlays/scots-lab/cluster/rook-ceph-cluster/