apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: multus
    name: multus
    tier: node
  name: kube-multus-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: multus
  template:
    metadata:
      labels:
        app: multus
        name: multus
        tier: node
    spec:
      containers:
      - command:
        - /usr/src/multus-cni/bin/multus-daemon
        env:
        - name: MULTUS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.2.2-thick
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - chattr -f +i /host/etc/cni/net.d/00-multus.conf || exit 0
        name: kube-multus
        securityContext:
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /tmp/multus
          name: multus-cni-config
        - mountPath: /host/etc/cni/net.d
          name: cni
        - mountPath: /opt/cni/bin
          name: cnibin
        - mountPath: /host/run
          name: host-run
        - mountPath: /var/lib/cni/multus
          name: host-var-lib-cni-multus
        - mountPath: /var/lib/kubelet
          mountPropagation: HostToContainer
          name: host-var-lib-kubelet
        - mountPath: /run/k8s.cni.cncf.io
          name: host-run-k8s-cni-cncf-io
        - mountPath: /run/netns
          mountPropagation: HostToContainer
          name: host-run-netns
        - mountPath: /etc/cni/net.d/multus.d
          name: multus-daemon-config
          readOnly: true
        - mountPath: /hostroot
          mountPropagation: HostToContainer
          name: hostroot
        - mountPath: /etc/cni/multus/net.d
          name: multus-conf-dir
      hostNetwork: true
      hostPID: true
      initContainers:
      - command:
        - /bin/sh
        - -c
        - chattr -f -i /host/etc/cni/net.d/00-multus.conf || exit 0
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.2.2-thick
        name: remove-multusconf-persistence
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
        securityContext:
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /host/etc/cni/net.d
          name: cni
      - command:
        - sh
        - -c
        - cp -f /usr/src/multus-cni/bin/multus-shim /host/opt/cni/bin/multus-shim
          && cp -f /usr/src/multus-cni/bin/passthru /host/opt/cni/bin/passthru
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.2.2-thick
        name: install-multus-binary
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
        securityContext:
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
          name: cnibin
      priorityClassName: system-node-critical
      serviceAccountName: multus
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - configMap:
          items:
          - key: 00-multus.conf
            path: 00-multus.conf
          name: multus-cni-config
        name: multus-cni-config
      - hostPath:
          path: /var/run/netns/
        name: host-run-netns
      - hostPath:
          path: /etc/cni/net.d
        name: cni
      - hostPath:
          path: /opt/cni/bin
        name: cnibin
      - hostPath:
          path: /
        name: hostroot
      - configMap:
          items:
          - key: daemon-config.json
            path: daemon-config.json
          name: multus-daemon-config
        name: multus-daemon-config
      - hostPath:
          path: /run
        name: host-run
      - hostPath:
          path: /var/lib/cni/multus
        name: host-var-lib-cni-multus
      - hostPath:
          path: /var/lib/kubelet
        name: host-var-lib-kubelet
      - hostPath:
          path: /run/k8s.cni.cncf.io
        name: host-run-k8s-cni-cncf-io
      - hostPath:
          path: /etc/cni/multus/net.d
        name: multus-conf-dir
  updateStrategy:
    type: RollingUpdate
