apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cluster/talos
generators:
  - ../../../../../helm/overlays/scots-lab/cluster/talos
  - generate-cluster-config.yaml