apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/infra/cilium/
generators:
  - ../../../../../helm/overlays/scots-lab/infra/cilium/
patches:
  - target:
      version: v1
      kind: Service
      name: hubble-ui
    path: hubble-ui-patch.yaml