apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/infra/multus/
  - multus-cni-config.yaml
patches:
  - path: multus-daemon-config-patch.yaml
    target:
      kind: ConfigMap
      version: v1
      name: multus-daemon-config    
  - path: kube-multus-ds-patch.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: kube-multus-ds