apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /spec/syncPolicy
    kind: Application
  project: default
  source:
    path: manifests/dev/apps/argocd-apps
    repoURL: https://github.com/ghubprime/k8s-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
