apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omni-dev
  namespace: argocd
spec:
  destination:
    namespace: omni-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{manifests/*}'
      recurse: true
    path: .
    repoURL: https://github.com/ghubprime/k8s-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
