apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-dev
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/scots-lab/apps/rook-ceph
    repoURL: https://github.com/ghubprime/k8s-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
