apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cluster/gateway-api-crds/
generators:
  - ../../../../../helm/overlays/scots-lab/cluster/gateway-api-crds/