apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/monitoring/kube-prometheus-stack/
generators:
  - ../../../../../helm/overlays/scots-lab/monitoring/kube-prometheus-stack/
patches:
  - patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: Replace=true
    target:
      kind: CustomResourceDefinition