apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  name: omnictl-cluster-sync-job
  namespace: talos-system
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - args:
        - cd repo/ && omnictl cluster template validate -f k8s-cluster.yaml && omnictl
          cluster template sync -f k8s-cluster.yaml
        command:
        - /bin/sh
        - -c
        env:
        - name: OMNI_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: omniEndpoint
              name: omni-api-key
        - name: OMNI_SERVICE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              key: omniServiceAccountKey
              name: omni-api-key
        image: ghcr.io/ghubprime/omnictl:v0.50.0
        name: cluster-template-sync
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - mountPath: /omni
          name: omni
      initContainers:
      - args:
        - git clone -n --depth=1 --filter=tree:0 https://github.com/ghubprime/k8s-cluster.git
          repo && cd repo && git sparse-checkout set --no-cone /k8s-cluster.yaml /bootstrap
          && git checkout
        command:
        - /bin/sh
        - -c
        env:
        - name: HOME
          value: /omni
        image: docker.io/alpine/git:v2.47.2
        name: clone-source-repo
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - mountPath: /omni
          name: omni
        workingDir: /omni
      restartPolicy: Never
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: Always
      volumes:
      - emptyDir:
          sizeLimit: 500Mi
        name: omni
