apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/apps/argocd/
generators:
  - ../../../../../helm/overlays/scots-lab/apps/argocd/
patches:
  - path: dashboard-patch.yaml